In [33]:
import gym
import numpy as np

env = gym.make('CartPole-v0')
observation = env.reset()
def run(env, policy, render = False):
    reward = 0
    observation = env.reset()
    done = False
    count = 0
    observations = [observation]
    while(done == False):        
        action = policy.step(observation, reward)            
        observation, reward, done, info = env.step(action)
        if(render):
            env.render()
        count += 1
        observations += [observation]
    return count, observations


In [7]:
class Policy(object):
    def step(self, observation, reward):
        return 0

In [42]:
policy = Policy()
obs = np.vstack([np.vstack(run(env, policy)[1]) for i in range(100)] )

In [43]:
import pandas as pd
pd.DataFrame(obs).describe()

0            1            2            3
count  1040.000000  1040.000000  1040.000000  1040.000000
mean     -0.053451    -0.926731     0.074749     1.414646
std       0.062775     0.593712     0.082334     0.928363
min      -0.246153    -2.163356    -0.050513    -0.048128
25%      -0.092839    -1.406699     0.008911     0.590899
50%      -0.043839    -0.950113     0.051926     1.415282
75%      -0.004112    -0.404916     0.131809     2.166169
max       0.049854     0.049982     0.264013     3.293350

In [54]:
class Policy(object):
    q = {}
    def step(self, observation, reward):
        weights = [0.062775 ,0.593712,0.082334,0.928363]  # std for each dimension
        normalized = observation / weights
        floored = np.floor(normalized)
        s = str(floored)
        
        
        
            
        
        print( s)
        return 0

run(env, Policy())

[-1. -1. -1. -1.]
[-1. -1. -1.  0.]
[-1. -1. -1.  0.]
[-1. -2. -1.  0.]
[-1. -2.  0.  1.]
[-1. -2.  0.  1.]
[-2. -3.  0.  1.]
[-2. -3.  1.  2.]
[-3. -3.  1.  2.]
[-3. -4.  2.  2.]


(10,
 [array([-0.01414351, -0.04662079, -0.02724291, -0.03781417]),
  array([-0.01507593, -0.2413417 , -0.02799919,  0.24615039]),
  array([-0.01990276, -0.4360528 , -0.02307618,  0.52987188]),
  array([-0.02862382, -0.63084266, -0.01247874,  0.81519507]),
  array([-0.04124067, -0.82579153,  0.00382516,  1.10392696]),
  array([-0.0577565 , -1.02096358,  0.0259037 ,  1.39780749]),
  array([-0.07817578, -1.2163979 ,  0.05385985,  1.69847545]),
  array([-0.10250373, -1.41209777,  0.08782936,  2.00742673]),
  array([-0.13074569, -1.6080177 ,  0.12797789,  2.32596251]),
  array([-0.16290604, -1.80404778,  0.17449714,  2.6551258 ]),
  array([-0.198987  , -1.99999556,  0.22759966,  2.99562617])])